### ISSUE TITLE
Permissions for nonroot - usb.core

### ISSUE THREAD

**Issue by tkelemen** [Tigge/openant#50]
Thanks for the awesome work on this project. 

I had a quick question about permissions for the usb.core package. The examples work when I used sudo, but I cannot figure out where to update the permissions to add other users/usergroups.
 
Thanks!

$ python3 heart_rate_monitor.py 
Driver available: [<class 'ant.base.driver.SerialDriver'>, <class 'ant.base.driver.USB2Driver'>, <class 'ant.base.driver.USB3Driver'>]
 - Using: <class 'ant.base.driver.USB3Driver'>
Traceback (most recent call last):
  File "heart_rate_monitor.py", line 69, in <module>
    main()
  File "heart_rate_monitor.py", line 49, in main
    node = Node()
  File "/usr/local/lib/python3.8/dist-packages/ant/easy/node.py", line 56, in __init__
    self.ant = Ant()
  File "/usr/local/lib/python3.8/dist-packages/ant/base/ant.py", line 68, in __init__
    self._driver.open()
  File "/usr/local/lib/python3.8/dist-packages/ant/base/driver.py", line 175, in open
    if dev.is_kernel_driver_active(0):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/usb/core.py", line 1061, in is_kernel_driver_active
    self._ctx.managed_open()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/usb/core.py", line 120, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/usb/backend/libusb1.py", line 786, in open_device
    return _DeviceHandle(dev)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/usb/backend/libusb1.py", line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

**Comment by Tigge** [comment]
Thank you. The `setup.py` tries to install udev rules to make the ANT devices available to all users. These can also be manually installed by running `sudo python setup.py udev_rules` or manually copying the file in `resources/` to your udev folder (usually `/etc/udev/rules.d` I think, but can depend on what system you are using).
